# Merge the spike & non-spike prediction files generated by logistic.spikes.absdiff.R

test.nospike  <- read.csv("pred.logistic.absdiffs.test.nospike.csv")
test.spike    <- read.csv("pred.logistic.absdiffs.test.spike.csv")
train.nospike <- read.csv("pred.logistic.absdiffs.train.nospike.csv")
train.spike   <- read.csv("pred.logistic.absdiffs.train.spike.csv")

test  <- rbind(test.spike,  test.nospike)
test  <- test[  order(test$TrialID,  test$ObsNum) ,]  # sort by TrialID then ObsNum

train <- rbind(train.spike, train.nospike)
train <- train[ order(train$TrialID, train$ObsNum) ,] 

write.csv(test,  file="pred.logistic.absdiffs.test.spikemerge.csv",row.names=FALSE, quote=FALSE)
write.csv(train, file="pred.logistic.absdiffs.train.spikemerge.csv",row.names=FALSE, quote=FALSE)


